# CC3001 Otoño 2021 Tarea 2
##Alumno Tomás Rivas

## Shellsort

### Profesores
Sección 1 Iván Sipirán •
Sección 2 Patricio Poblete •
Sección 3 Nelson Baloian


El objetivo de esta tarea es que usted implemente el algoritmo de ordenación Shellsort.

Para describir cómo funciona Shellsort definamos un arreglo "$d$-ordenado" (donde $d$ es un entero mayor o igual a 1) como un arreglo en que cada elemento está ordenado respecto de sus vecinos que están a $d$ casilleros de distancia. Por ejemplo, en el siguiente diagrama se muestran un arreglo antes y después de ser "3-ordenado", destacando en distintos colores las las subsecuencias que se forman al considerar elementos que están a distancia 3:

Antes:

![shellsort1](https://github.com/ppoblete/CC3001-2020-2-Tareas/blob/master/shellsort1.png?raw=1)

Después:

![shellsort2](https://github.com/ppoblete/CC3001-2020-2-Tareas/blob/master/shellsort2.png?raw=1)

Noten que el caso particular de un arreglo "1-ordenado" (caso $d=1$) sería lo mismo que un arreglo ordenado.

El algoritmo Shellsort consiste en hacer una secuencia de pasadas $d$-ordenando el arreglo, cada vez con un valor diferente de $d$, siendo la última siempre con $d=1$.

Para hacer una pasada de Shellsort elegimos un valor de $d$ y luego aplicamos una versión modificada de ordenación por inserción. La modificación consiste en que la función ``insertar(a,k)`` compara con el elemento $d$ casilleros más atrás, en lugar de hacerlo con el que está uno más atrás.

Para ordenar el arreglo completo, Shellsort hace una secuencia de pasadas, con un conjunto decreciente de valores $d_k,d_{k-1}, \ldots,d_1$, con $d_1=1$. Esto último asegura que el arreglo quede finalmente ordenado, pero las pasadas anteriores contribuyen a acelerar el proceso, porque hay un teorema (que no les pedimos demostrar) que dice que si un arreglo que ya estaba $i$-ordenado se $j$-ordena, el arreglo resultante sigue estando $i$-ordenado. Esto es, una pasada no echa a perder lo que han hecho las anteriores.

# Recuerdo de la ordenación por inserción

Recuerde que la ordenación por inserción está implementada en el apunte de la manera siguiente:

In [ ]:
def ordena_insercion(a):
    """Ordena el arreglo a por inserción"""
    n=len(a)
    print(a)
    for k in range(0,n):
        insertar(a,k)   
def insertar(a, k):
    """
    Inserta a[k] entre los elementos anteriores
    preservando el orden ascendente (versión 2)
    """
    b=a[k] # b almacena transitoriamente al elemento a[k]
    j=k # señala la posición del lugar "vacío"
    while j>0 and b<a[j-1]:
        a[j]=a[j-1]
        j-=1
    a[j]=b

Probemos esto para asegurarnos que funcione bien:

In [ ]:
import numpy as np

def verifica_d_ordenado(a,d):
    for i in range(0,len(a)-d):
        assert a[i]<=a[i+d]
    print("Arreglo "+str(d)+"-ordenado OK.")
        
A = np.array([46,35,95,21,82,70,72,56,64,50])
ordena_insercion(A)
print(A)
verifica_d_ordenado(A,1)

[46 35 95 21 82 70 72 56 64 50]
[21 35 46 50 56 64 70 72 82 95]
Arreglo 1-ordenado OK.


---
# Lo que usted tiene que hacer:

## 1) Programar una $d$-ordenación

Modifique el código anterior para que $d$-ordene el arreglo, para un valor de $d$ dado. Para esto, escriba el código de la función ``d_insertar`` en el espacio provisto:

Para crear esta función, como necesitamos que se d-ordene, en vez de comparar con el elemento anterior (a[j-1]) tenemos que comparar con el elemento que esta “d” casillas más atrás, es decir el elemento a[j-d]. Además, necesitamos parar la recursividad cuando no quede un elemente d casillas mas atrás, es decir si estamos haciendo un ordenamiento con d= 5 y estamos en la casilla 4 no podemos seguir ya que si le restamos d a 4 nos queda fuera del arreglo. Es por esto que usamos j//d>0; ya que esto significa que d aun cabe dentro de j y por lo tanto podemos restar d a j sin temor a quedar fuera del arreglo. Sumando estas 2 condiciones armamos el while:

**while j//d>0 and b<a[j-d]:**

Además el cambio ahora lo tenemos que hacer por a[j-d] que es el elemento con el que estamos comparando por lo que nos queda a[j]=a[j-d] y para seguir comparando tenemos que bajarle d a j por lo que ponemos j=j-d. Finalmente al igual que en el código de insertar normal terminamos con un a[j]=b fuera de la recursividad para cuando ya no se cumpla alguna de las condiciones del while.

Con todo esto y usando de base el código de insertar armamos la función:

In [ ]:
def d_ordena_insercion(a,d):
    """d-Ordena el arreglo a por inserción"""
    n=len(a)
    for k in range(0,n):
        d_insertar(a,k,d)    
def d_insertar(a,k,d):
    b=a[k] # b almacena transitoriamente al elemento a[k]
    j=k # señala la posición del lugar "vacío"
    while j//d>0 and b<a[j-d]: #El while con las nuevas condiciones
        a[j]=a[j-d] #El nuevo cambio
        j=j-d
    a[j]=b 

Pruebe aquí que su algoritmo $3$-ordena correctamente:

In [ ]:
A = np.array([46,35,95,21,82,70,72,56,64,50])
d_ordena_insercion(A,3)


In [ ]:
A = np.array([46,35,95,21,82,70,72,56,64,50])
d_ordena_insercion(A,3)
print(A)
verifica_d_ordenado(A,3)

[21 35 64 46 56 70 50 82 95 72]
Arreglo 3-ordenado OK.


**Concluimos que el algoritmo lo ordeno correctamente**

## 2) Programar Shellsort

Con esto ya estamos listos para programar Shellsort, haciendo una secuencia de pasadas, variando el valor de $d$ y terminando con $d=1$.Hay muchas formas conocidas de generar la secuencia de valores de $d$, con variados niveles de eficiencia. A continuación, programe Shellsort usando una secuencia decreciente de valores de la forma $d_k=2^k-1$, esto es: $\ldots, 63, 31, 15, 7, 3, 1$. Se sabe que esta secuencia hace que Shellsort funcione en tiempo $\Theta(n^{3/2})$:

Para programar el Shellsort, primero creare una lista con todos los “d” menores al largo de el array. Esto creando un while que funcione mientras los $d_k=2^k-1$ sean menores que el largo, partiendo con k = 1 y aumentando el k de a uno en uno. Con los elementos que vayan cumpliendo esta condición,no los k si no los $d_k=2^k-1$, los iremos agregando a una lista que partira vacia y terminara con todos los D$_k$ que nos sirvan.Ahora esta lista hay que invertirla ya que parte con 1 y termina con el D$_k$ mayor, por lo que la invertiremos usando reverse.
 
 Luego usando un for para recorrer los elementos de esta lista en orden, d-ordenaremos el arreglo con cada uno de los D$_k$.

In [ ]:
def Shellsort(a):
    """Ordena a usando Shell Sort, con la secuencia de valores …,63,31,15,7,3,1"""
    k=1
    p =[]
    while 2**k-1<=len(a):
          p.append(2**k-1)
          k=k+1
    p.reverse()
    for i in p:
        d_ordena_insercion(a,i)
 

Pruebe aquí su algoritmo de la manera siguiente:

In [ ]:
A = np.array([46,35,95,21,82,70,72,56,64,50])
Shellsort(A)

In [ ]:
A = np.array([46,35,95,21,82,70,72,56,64,50])
Shellsort(A)
print(A)
verifica_d_ordenado(A,1)

[21 35 46 50 56 64 70 72 82 95]
Arreglo 1-ordenado OK.


Observamos que el arreglo quedo correctamente ordenado.

En la siguiente celda agregue una prueba similar de ordenación de un arreglo de tamaño $1000$ generado al azar (sin imprimirlo):

Ahora para generar esta lista aleatoria usaremos random.randint por lo que primero importamos random con import random, y luego partiendo de una lista vacía y usando un for de rango 1000, le vamos agregando elementos a esta lista con random.randint(0,100), entre 0 y 100. Finalmente usamos Shellsort y verificamos que funcione.

In [ ]:
import random
m=[]
for i in range (0,999):
    m.append(random.randint(0,100))
Shellsort(m)
verifica_d_ordenado(m,1)

Arreglo 1-ordenado OK.


Funciono correctamente

## 3) Probar con una secuencia diferente de valores $d_k$

Finalmente, investigue respecto de otras maneras de generar la secuencia $d_k$, escoja una secuencia en particular, modifique su versión de Shellsort que la use y pruébela.

Para esta sección usare la serie formada por $d_k=\dfrac{3^k-1}{2}$ y modificare el codigo de Shellsort para que use esta serie.

In [ ]:
def Shellsort2(a):
    #Shellsort con la otra serie.
    k=1
    p =[]
    while (3**k-1)//2<=len(a):
          p.append((3**k-1)//2)
          k=k+1
    p.reverse()
    for i in p:
        d_ordena_insercion(a,i)
 

Ahora usando la lista randomizada de antes probamos el nuevo código.

In [ ]:
import random
m=[]
for i in range (0,999):
    m.append(random.randint(0,100))
Shellsort2(m)
print(m)
verifica_d_ordenado(m,1)

[0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 28, 28

Después de correr el código varias veces correctamente, podemos decir que esta serie también funciona para usar en el Shellsort.

Con esto queda concluida la tarea. 

Alumno:  Tomás Rivas

Rut:  20.592.350-0